title: Thuyen's corner
email: trinhngocthuyen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trinhngocthuyen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: trinhngocthuyen
github_username:  trinhngocthuyen

# Build settings
markdown: kramdown
theme: minima

sass:
  sass_dir:  _scss
  # style:    :compressed

# Permalinks
permalink: '/:year-:month-:day-:title.html'

# Pagination
paginate: 10
paginate_path: '/page:num/'
excerpt_separator: <!--more-->

# Disqus
comments: true

gems:
  - jekyll-feed
  - jekyll-paginate

# Include

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  misc:
    output: true
  reasoning:
    output: true


